"""GWZ transport owner conversation schema.

Bootstrap envelopes use profile version 1; a successful Bound may negotiate
profile version 2 for all subsequent messages.
"""
from taut.ir.dsl import BOOL, BYTES, INT, STR, Enum, F, List, Msg, Ref, schema

SCHEMA = schema(
    MessageKind=Enum(bind=1, bound=2, bind_rejected=3, open=4, opened=5,
                     open_failed=6, data=7, window=8, flush=9, flushed=10,
                     end_write=11, close=12, closed=13, cancel=14, failed=15,
                     check_identity=16, identity_checked=17,
                     identity_check_failed=18),
    EndpointRole=Enum(local=1, driver=2),
    Scheme=Enum(ssh=1, https=2),
    AuthPolicy=Enum(ssh_ambient=1, ssh_explicit=2, anonymous=3, gh=4),
    GitService=Enum(upload_pack_advertisement=1, upload_pack_exchange=2,
                    receive_pack_advertisement=3, receive_pack_exchange=4),
    IdentityMode=Enum(ambient=1, explicit_key=2, credentials_disabled=3),
    ErrorCode=Enum(unsupported_version=1, unsupported_operation=2, unavailable=3,
                   invalid_request=4, capacity=5, timeout=6, cancelled=7,
                   authentication=8, trust=9, io=10, protocol=11, carrier_lost=12,
                   repository_refused=13),
    SetupFailureCause=Enum(stall=1, aggregate=2, interaction=3,
                           allocation=4, connection_refused=5, not_found=6,
                           address_not_available=7),
    Effect=Enum(none=1, possible=2),
    Disposition=Enum(reusable=1, discarded=2),
    AuthMethod=Enum(none=1, ssh_agent=2, ssh_key=3, gh=4),
    Limits=Msg(
        encoded_frame=F(1, INT), data_payload=F(2, INT), metadata_bytes=F(3, INT),
        nesting=F(4, INT), collection_entries=F(5, INT), decode_allocation=F(6, INT),
        queued_bytes=F(7, INT), queued_frames=F(8, INT), receive_window=F(9, INT),
        control_reserve_bytes=F(10, INT), control_reserve_frames=F(11, INT)),
    Bind=Msg(versions=F(1, List(INT)), role=F(2, Ref.EndpointRole),
             schemes=F(3, List(Ref.Scheme)), policies=F(4, List(Ref.AuthPolicy)),
             receive_limits=F(5, Ref.Limits)),
    Bound=Msg(version=F(1, INT), endpoint_id=F(2, STR), role=F(3, Ref.EndpointRole),
              schemes=F(4, List(Ref.Scheme)), policies=F(5, List(Ref.AuthPolicy)),
              receive_limits=F(6, Ref.Limits), trust_owner=F(7, STR)),
    Failure=Msg(code=F(1, Ref.ErrorCode), effect=F(2, Ref.Effect),
                facts=F(3, Ref.Facts, optional=True, missing_ok=True),
                setup_cause=F(4, Ref.SetupFailureCause, optional=True, missing_ok=True)),
    Destination=Msg(scheme=F(1, Ref.Scheme), host=F(2, STR), port=F(3, INT),
                    path=F(4, STR), ssh_username=F(5, STR, optional=True)),
    Identity=Msg(mode=F(1, Ref.IdentityMode), key_path=F(2, STR, optional=True),
                 path_base=F(3, STR, optional=True)),
    Deadlines=Msg(allocation_ms=F(1, INT), connect_ms=F(2, INT),
                  io_ms=F(3, INT), interaction_ms=F(4, INT), cleanup_ms=F(5, INT)),
    Open=Msg(endpoint_id=F(1, STR), operation_id=F(2, STR),
             destination=F(3, Ref.Destination), service=F(4, Ref.GitService),
             identity=F(5, Ref.Identity), policy=F(6, Ref.AuthPolicy),
             deadlines=F(7, Ref.Deadlines), receive_limits=F(8, Ref.Limits)),
    CheckIdentity=Msg(endpoint_id=F(1, STR), operation_id=F(2, STR),
                      identity=F(3, Ref.Identity), timeout_ms=F(4, INT)),
    IdentityChecked=Msg(),
    Facts=Msg(method=F(1, Ref.AuthMethod), credential_offered=F(2, BOOL),
              authenticated=F(3, BOOL, optional=True),
              key_fingerprint=F(4, STR, optional=True),
              http_status=F(5, INT, optional=True), ssh_exit_status=F(6, INT, optional=True)),
    Opened=Msg(connection_id=F(1, STR), reused=F(2, BOOL), endpoint_id=F(3, STR),
               trust_owner=F(4, STR), facts=F(5, Ref.Facts), receive_limits=F(6, Ref.Limits)),
    Data=Msg(offset=F(1, INT), payload=F(2, BYTES)),
    Window=Msg(max_offset=F(1, INT)),
    Barrier=Msg(barrier_id=F(1, INT), offset=F(2, INT)),
    EndWrite=Msg(final_offset=F(1, INT)),
    Close=Msg(final_offset=F(1, INT)),
    Closed=Msg(disposition=F(1, Ref.Disposition), unread_response_discarded=F(2, BOOL),
               facts=F(3, Ref.Facts), failure=F(4, Ref.Failure, optional=True)),
    Cancel=Msg(reason=F(1, Ref.ErrorCode)),
    # Exactly one body must match kind. Optional taut fields encode absent as null.
    Envelope=Msg(version=F(1, INT), session_id=F(2, STR), stream_id=F(3, INT),
                 kind=F(4, Ref.MessageKind),
                 bind=F(10, Ref.Bind, optional=True), bound=F(11, Ref.Bound, optional=True),
                 bind_rejected=F(12, Ref.Failure, optional=True),
                 open=F(13, Ref.Open, optional=True), opened=F(14, Ref.Opened, optional=True),
                 open_failed=F(15, Ref.Failure, optional=True),
                 data=F(16, Ref.Data, optional=True), window=F(17, Ref.Window, optional=True),
                 flush=F(18, Ref.Barrier, optional=True), flushed=F(19, Ref.Barrier, optional=True),
                 end_write=F(20, Ref.EndWrite, optional=True), close=F(21, Ref.Close, optional=True),
                 closed=F(22, Ref.Closed, optional=True), cancel=F(23, Ref.Cancel, optional=True),
                 failed=F(24, Ref.Failure, optional=True),
                 check_identity=F(25, Ref.CheckIdentity, optional=True, missing_ok=True),
                 identity_checked=F(26, Ref.IdentityChecked, optional=True, missing_ok=True),
                 identity_check_failed=F(27, Ref.Failure, optional=True, missing_ok=True)),
)
